name: flow

on:
  - push
  - pull_request

permissions: read-all

jobs:
  lab2:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14
          dune-cache: true

      - run: opam install . --deps-only --with-test
      - run: opam install zanuda
      - run: opam install ounit2
      - run: rm -rf _build
      - run: opam exec -- dune build @fmt @check @runtest -j3
      - run: opam exec -- dune runtest
      - run: opam exec -- zanuda -no-top_file_license -no-check-filesystem -dir .
